services:
  app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - laravel-net

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - laravel-net
    volumes:
      - dbdata:/var/lib/mysql

  webserver:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - "5500:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net

networks:
  laravel-net:

volumes:
  dbdata: